[package]
name = "multidown"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full", "rt-multi-thread", "macros"] }
url = "2.5"
anyhow = "1.0"